name: textile_defect_app
description: A Flutter app for car price prediction using Gemini API.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  image_picker: ^1.0.4
  google_fonts: ^6.1.0
  flutter_dotenv: ^5.1.0
  uuid: ^4.5.1
  firebase_storage: ^12.4.4
  cloud_firestore: ^5.6.5
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  flutter_launcher_icons: ^0.14.3
  intl: ^0.19.0
  url_launcher: ^6.2.5
  flutter_svg: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/car_icon.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - .env
